# Используем официальный образ CloudBeaver
FROM dbeaver/cloudbeaver:latest

# Открываем порт для веб-интерфейса
EXPOSE 8978

# Указываем точку монтирования для сохранения настроек и подключений
VOLUME /opt/cloudbeaver/workspace